// <auto-generated />
namespace NewLeague.Domain.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class init4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(init4));
        
        string IMigrationMetadata.Id
        {
            get { return "201508090625052_init4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
