// <auto-generated />
namespace NewLeague.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class userinfo2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(userinfo2));
        
        string IMigrationMetadata.Id
        {
            get { return "201603131356339_userinfo2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
